apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app : {{ .Values.replicaSpec.matchLabels.app }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.containerSpec.port }}
      port: {{ .Values.service.port }} 
