apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-ds
spec:
  selector:
    matchLabels:
      name: flunetd
  template:
    metadata:
      labels:
        name: flunetd
    spec:
      containers:
      - name: flunetd
        image: gcr.io/google-containers/fluentd-elasticsearch:1.20